CREATE TABLE IF NOT EXISTS auth.token (
    id SERIAL PRIMARY KEY,
    data VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    user_id INTEGER REFERENCES app.user(id) ON DELETE CASCADE NOT NULL
);