CREATE TABLE IF NOT EXISTS auth.token (
    id SERIAL PRIMARY KEY,
    data UUID NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    user_id INTEGER REFERENCES auth.user(id) ON DELETE CASCADE NOT NULL
);